version: 0.1

phases:
  pre_build:
    commands:
      - echo "pre build"
      - find . -name '*.sh' -type f | xargs chmod +x
      - npm i
      - (cd lambda; npm i)
  build:
    commands:
      - echo "build"
      - CI=true npm test
      - CI=true npm run build
      - ./lambda/build.sh
      - ./operations/cd-publish.sh
  post_build:
    commands:
      - echo "post build"

