AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    Username:
      Type: String
      MinLength: 1
      NoEcho: true
    EmailAddress:
      Type: String
      MinLength: 1
      NoEcho: true

Resources:
  Users:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        UnusedAccountValidityDays: 90
      AliasAttributes:
        - email
        - preferred_username
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: true
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 10
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: false
          Name: email
          Required: true
      UserPoolName: !Sub users-${AWS::StackName}

  PresentationClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      GenerateSecret: false
      ReadAttributes:
        - email
      RefreshTokenValidity: 30
      UserPoolId: !Ref Users

  InitialUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref EmailAddress
      Username: !Ref Username
      UserPoolId: !Ref Users

  Identities:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      # DeveloperProviderName: String   ### might need this <--------
      CognitoIdentityProviders:
        - ClientId: !Ref PresentationClient
          ProviderName: !GetAtt Users.ProviderName

  AuthenticatedIdentityRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
                Federated: cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref Identities
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: pipeline
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "cloudformation:*"
                Resource:
                  - "*"

  UnauthenticatedIdentityRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
                Federated: cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref Identities
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: pipeline
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                Action:
                  - "*"
                Resource:
                  - "*"

  AuthenticatedRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    DependsOn:
      - UnauthenticatedIdentityRole
      - AuthenticatedIdentityRole
    Properties:
      IdentityPoolId: !Ref Identities
      Roles:
        authenticated: !GetAtt AuthenticatedIdentityRole.Arn
        unauthenticated: !GetAtt UnauthenticatedIdentityRole.Arn

Outputs:
  UserPool:
    Value: !Ref Users
  PresentationClient:
    Value: !Ref PresentationClient
  IdentityPool:
    Value: !Ref Identities
