AWSTemplateFormatVersion: '2010-09-09'

Resources:

    ArtifactStore:
        Type: AWS::S3::Bucket

    SourceStore:
        Type: AWS::S3::Bucket

    PipelineRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    Effect: Allow
                    Action: sts:AssumeRole
                    Principal:
                        Service: codepipeline.amazonaws.com
            Policies:
              - PolicyName: pipeline
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - codebuild:*
                        Resource:
                          !GetAtt FrontendBuilder.Arn
                      - Effect: Allow
                        Action:
                          - s3:getObject
                        Resource:
                          - !GetAtt SourceStore.Arn
                          - !Sub ${SourceStore.Arn}/*
                      - Effect: Allow
                        Action:
                          - s3:GetObject
                          - s3:ListObjects
                          - s3:PutObject
                        Resource:
                          - !GetAtt ArtifactStore.Arn
                          - !Sub ${ArtifactStore.Arn}/*

    BuildRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    Effect: Allow
                    Action: sts:AssumeRole
                    Principal:
                        Service: codebuild.amazonaws.com
            Policies:
              - PolicyName: artifact-store
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - s3:GetObject
                          - s3:GetObjectVersion
                          - s3:PutObject
                        Resource:
                          - !GetAtt ArtifactStore.Arn
                          - !Sub ${ArtifactStore.Arn}/*
                          - arn:aws:s3:::operations-area-frontend-websiteorigin-1rtgo36nz66i0
                          - arn:aws:s3:::operations-area-frontend-websiteorigin-1rtgo36nz66i0/*
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                        Resource: "*"


    FrontendPipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            ArtifactStore:
                Location: !Ref ArtifactStore
                Type: S3
            RoleArn: !GetAtt PipelineRole.Arn
            RestartExecutionOnUpdate: false
            Stages:
              - Name: Source
                Actions:
                  - Name: Source
                    ActionTypeId:
                        Category: Source
                        Owner: AWS
                        Version: 1
                        Provider: S3
                    OutputArtifacts:
                        - Name: Operations-Frontend-Source
                    Configuration:
                        S3Bucket: !Ref SourceStore
                        S3ObjectKey: frontend-master.zip
                    RunOrder: 1
              - Name: Build
                Actions:
                  - Name: Build
                    ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Version: 1
                        Provider: CodeBuild
                    Configuration:
                        ProjectName: !Ref FrontendBuilder
                    InputArtifacts:
                      - Name: Operations-Frontend-Source
                    OutputArtifacts:
                      - Name: Operations-Frontend-Deployable
                    RunOrder: 2

    FrontendBuilder:
        Type: AWS::CodeBuild::Project
        Properties:
            Artifacts:
                Location: !Ref ArtifactStore
                Type: S3
            Source:
                Location: !Sub ${ArtifactStore}/Operations-Frontend-Source
                Type: S3
            Environment:
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/nodejs:8.11.0
                Type: LINUX_CONTAINER
                EnvironmentVariables:
                  - Name: AWS_DEFAULT_REGION
                    Value: !Ref AWS::Region
                  - Name: CI
                    # has to be false because of warnings from dependency
                    Value: "false"
            Name: !Sub frontend-${AWS::StackName}
            ServiceRole: !Ref BuildRole

  # Access for outside deployer i.e. Jenkins
    DeployerPseudoUser:
        Type: AWS::IAM::User
        Properties:
            Policies:
              - PolicyName: deployerUser
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - s3:PutObject
                        Resource:
                          - !Sub "${SourceStore.Arn}/*"

    DeployerPseudoUserAccessKey:
        Type: "AWS::IAM::AccessKey"
        Properties:
            Serial: 1
            UserName: !Ref DeployerPseudoUser

Outputs:
    DeployerAccessKey:
        Value: !Ref DeployerPseudoUserAccessKey
    DeployerSecretAccessKey:
        Value: !GetAtt DeployerPseudoUserAccessKey.SecretAccessKey






